spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spandan_recipe?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: sfg_dev_user
    password: Spandan
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
#    properties:
#     javax:
#       persistence:
#         schema-generation:
#           create-source: metadata
#           scripts:
#             action: create
#             create-target: spandan_database_create.sql