spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sfg_prod?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
        username: sfg_prod_user
        password: Spandan
        platform: mysql
    jpa:
        hibernate:
            ddl-auto: validate
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: mysql
        show-sql: true